--CREATE DATABASE ProyectoSBD;

CREATE TABLE INVENTARIO(
	IdInventario SERIAL,
	Descripcion VARCHAR(50),
	Cantidad INT,
	
	CONSTRAINT INV_PK PRIMARY KEY(IdInventario)
);

CREATE TABLE TRABAJADOR(
	IdTrabajador SERIAL,
	Nombre VARCHAR(15),
	ApellidoP VARCHAR(20),
	ApellidoM VARCHAR(20),
	Telefono VARCHAR(15),
	IdInventario INT,
	
	CONSTRAINT TRAB_PK PRIMARY KEY(IdTrabajador),
	CONSTRAINT TRAB_INV_FK FOREIGN KEY (IdInventario) REFERENCES INVENTARIO(IdInventario) ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	IdCliente SERIAL,
	IdTrabajador INT,
	Nombre VARCHAR(25),
	ApellidoP VARCHAR(25),
	ApellidoM VARCHAR(25),
	Calle VARCHAR(25),
	Colonia VARCHAR(35),
	CodigoPostal VARCHAR(10),
	NumExt VARCHAR(10),
	NumInt VARCHAR(10),
	Telefono VARCHAR(15),
	Correo VARCHAR(45),
	
	CONSTRAINT CLIENT_PK PRIMARY KEY (IdCliente),
	CONSTRAINT CLIENT_TRAB_FK FOREIGN KEY (IdTrabajador) REFERENCES Trabajador(IdTrabajador) ON DELETE CASCADE
);

CREATE TABLE CITA(
	IdCita SERIAL,
	IdCliente INT,
	Fecha DATE,
	Cotizacion DECIMAL(10,2),
	Descripcion VARCHAR(140),
	Lugar VARCHAR(140),
	
	CONSTRAINT CITA_PK PRIMARY KEY(IdCita),
	CONSTRAINT CITA_CLIENT_FK FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente) ON DELETE CASCADE
);

CREATE TABLE EQUIPO(
	IdEquipo SERIAL,
	IdCliente INT,
	HP_Compresor VARCHAR(40),
	Voltaje VARCHAR(10),
	Marca VARCHAR(15),
	Capacidad VARCHAR(10),
	Descripcion VARCHAR(140),
	HP_Ventiladores INT,
	
	CONSTRAINT EQUIPO_PK PRIMARY KEY (IdEquipo),
	CONSTRAINT EQUIPO_CLIENT_FK FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente) ON DELETE CASCADE
);

CREATE TABLE HISTORIAL(
	IdHistorial SERIAL,
	IdCliente INT,
	Fecha DATE,
	Costo INT,
	Descripcion VARCHAR(140),

	CONSTRAINT HISTORIAL_PK PRIMARY KEY (IdHistorial),
	CONSTRAINT HISTORIAL_CLIENT_FK FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente) ON DELETE CASCADE
);

CREATE TABLE FACTURA(
	IdFactura SERIAL,
	IdHistorial INT,
	IdCliente INT,
	Fecha DATE,
	Costo INT,
	RFC VARCHAR(13),
	Descripcion VARCHAR(140),
	Metodo_Pago VARCHAR(30),

	CONSTRAINT FACTURA_PK PRIMARY KEY (IdFactura),
	CONSTRAINT FACTURA_CLIENT_FK FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente) ON DELETE CASCADE,
	CONSTRAINT FACTURA_HISTORIAL_FK FOREIGN KEY (IdHistorial) REFERENCES HISTORIAL(IdHistorial) ON DELETE CASCADE
);

CREATE TABLE CREDITO(
	IdCredito SERIAL,
	IdCliente INT,
	Fecha DATE,
	LimitePago DATE,

	CONSTRAINT CREDITO_PK PRIMARY KEY (IdCredito),
	CONSTRAINT EQUIPO_CLIENT_FK FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente) ON DELETE CASCADE
);

CREATE TABLE ABONOS(
	IdAbonos SERIAL,
	IdCredito INT,
	Monto INT,
	TotalAPagar INT,
	CONSTRAINT ABONOS_PK PRIMARY KEY (IdCredito),
	CONSTRAINT ABONO_CREDITO_FK FOREIGN KEY (IdCredito) REFERENCES CREDITO(IdCredito) ON DELETE CASCADE
);